### ISSUE TITLE
ModuleNotFoundError: No module named 'libknxmap'

### ISSUE THREAD

**Issue by ichbinder** [takeshixx/knxmap#7]
Hi,
I try to start knxmap under Fedora 27 with python 3.6 but I get following error:

`Traceback (most recent call last):
  File "/usr/bin/knxmap", line 11, in <module>
    load_entry_point('KNXmap==0.10.0', 'console_scripts', 'knxmap')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 563, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2651, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2305, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2311, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/bin/knxmap.py", line 7, in <module>
    from libknxmap import KnxMap, Targets, KnxTargets
ModuleNotFoundError: No module named 'libknxmap'`

I installed knxmap with: sudo ./setup.py install
can you help me?

**Comment by takeshixx** [comment]
Thanks for reporting this issue. Have you tried it with the recent master? I've renamed the module a while ago, maybe you still have Python cache files in the module directory.
